### ISSUE TITLE
spx3819m5-l-3-3_tr 문서

### ISSUE THREAD

**Issue by elpusk** [elpusk/report.lpu237#11]
spx3819m5-l-3-3_tr 문서를 자세히 보니깐 기본 베이스가 Declaration 문서이고 RohS II, Reach 지침 사항 및 정보만 나와 있습니다. 정상적인 시험 결과
Report가 아닙니다. 

하기 내용 참고 하시면 “ROHS 규제 제제 사항 및 Reach 관련 화학물질 추가개정 이력, 화학물질 정보”

등만 확인 가능함, 정상적인 ROHS 시험 정보는 없음, 관련 문서는 Doc용으로밖에 사용 할 수 없음

정상적인 문서의 경우 시험 결과 Report가 하기 내용처럼 기입되어 있음.

예를 들어 Reach의 일반적인 Coc. 문서의 경우 (정상)
예를 들어 RohS II의 일반적인 Coc. 문서의 경우 (정상)
참고 하시기 바랍니다.

**Comment by ssyang** [comment]
maxlinear 홈페이지에 문의 중 인데 아직 응답없음.
CAS-03715-W8B3X4
2020.12.09

**Comment by ssyang** [comment]
85507db commit  에서 maxliner 에서 받은 문서로 보안함.
